# -*- coding: utf-8 -*-
"""ShAI_BootCamp_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SaiGEe-4cVL0hlBRUox8RktQQDo9LaU8

#About Dataset
salaries dataset generally provides information about the employees of an organization in relation to their compensation. It typically includes details such as how much each employee is paid (their salary), their job titles, the departments they work in, and possibly additional information like their level of experience, education, and employment history within the organization.

# Features
- 'Id'
- 'EmployeeName'
- 'JobTitle'
- 'BasePay'
- 'OvertimePay'
- 'OtherPay'
- 'Benefits'
- 'TotalPay' -> salary
- 'TotalPayBenefits'
- 'Year'
- 'Notes'
- 'Agency'
- 'Status'

# Tasks

1. **Basic Data Exploration**: Identify the number of rows and columns in the dataset, determine the data types of each column, and check for missing values in each column.

2. **Descriptive Statistics**: Calculate basic statistics mean, median, mode, minimum, and maximum salary, determine the range of salaries, and find the standard deviation.

3. **Data Cleaning**: Handle missing data by suitable method with explain why you use it.

4. **Basic Data Visualization**: Create histograms or bar charts to visualize the distribution of salaries, and use pie charts to represent the proportion of employees in different departments.

5. **Grouped Analysis**: Group the data by one or more columns and calculate summary statistics for each group, and compare the average salaries across different groups.

6. **Simple Correlation Analysis**: Identify any correlation between salary and another numerical column, and plot a scatter plot to visualize the relationship.

8. **Summary of Insights**: Write a brief report summarizing the findings and insights from the analyses.

# Very Important Note
There is no fixed or singular solution for this assignment, so if anything is not clear, please do what you understand and provide an explanation.
"""

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/Salaries.csv')
df.head()

df.columns

num_rows, num_columns = df.shape
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")



data_types = df.dtypes
print("\nData types of each column:")
print(data_types)



missing_values = df.isnull().sum()
print("\nMissing values in each column:")
print(missing_values)



base_pay_stats = df['BasePay'].describe()

mean_salary = df['BasePay'].mean()
median_salary = df['BasePay'].median()
mode_salary = df['BasePay'].mode()[0]
min_salary = df['BasePay'].min()
max_salary = df['BasePay'].max()
salary_range = max_salary - min_salary
std_dev_salary = df['BasePay'].std()


print("Basic Statistics for BasePay:")
print(base_pay_stats)
print("\nAdditional Statistics:")
print(f"Mean Salary: {mean_salary}")
print(f"Median Salary: {median_salary}")
print(f"Mode Salary: {mode_salary}")
print(f"Minimum Salary: {min_salary}")
print(f"Maximum Salary: {max_salary}")
print(f"Salary Range: {salary_range}")
print(f"Standard Deviation of Salary: {std_dev_salary}")

df.dropna(inplace=True)
df['BasePay'].fillna(df['BasePay'].mean(), inplace=True)
if not df['JobTitle'].mode().empty:
    df['JobTitle'].fillna(df['JobTitle'].mode()[0], inplace=True)
else:
    print("No mode found for 'JobTitle'")

import matplotlib.pyplot as plt
import pandas as pd

plt.figure(figsize=(10, 6))
plt.hist(df['BasePay'], bins=20, color='blue', edgecolor='black')
plt.title('BasePay Distribution')
plt.xlabel('BasePay')
plt.ylabel('Frequency')
plt.show()


jobtitle_counts = df['JobTitle'].value_counts().head(10)
plt.figure(figsize=(10, 6))
plt.bar(jobtitle_counts.index, jobtitle_counts.values, color='green')
plt.title('Employee Distribution by Job Title (Top 10)')
plt.xlabel('Job Title')
plt.ylabel('Number of Employees')
plt.xticks(rotation=45, ha='right')
plt.show()


plt.figure(figsize=(8, 8))
plt.pie(jobtitle_counts, labels=jobtitle_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Proportion of Employees by Job Title (Top 10)')
plt.show()

import pandas as pd


grouped_data = df.groupby(['JobTitle', 'Year'])


summary_stats = grouped_data['BasePay'].agg(['mean', 'median', 'min', 'max', 'std', 'count']).reset_index()


print(summary_stats)


average_salaries_comparison = summary_stats.pivot(index='JobTitle', columns='Year', values='mean')


print(average_salaries_comparison)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


correlation_data = df[['BasePay', 'TotalPay']]


correlation_matrix = correlation_data.corr()


sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix')
plt.show()


plt.figure(figsize=(10, 6))
sns.scatterplot(x='BasePay', y='TotalPay', data=df, alpha=0.5)
plt.title('Scatter Plot of BasePay vs TotalPay')
plt.xlabel('BasePay')
plt.ylabel('TotalPay')
plt.show()

